# Generated by Django 6.1.1 on 2026-10-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiveditem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsreceiveditem',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
