# Generated by Django 6.0.7 on 2026-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PHARMACIST', 'Pharmacist'), ('STOCK_CLERK', 'Stock Clerk'), ('STORE_MANAGER', 'Store Manager')], default='STOCK_CLERK', max_length=20),
        ),
    ]
