# Generated by Django 6.1.2 on 2026-10-08 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('LOGIN', 'Signed in'), ('LOGOUT', 'Signed out'), ('PROFILE_UPDATED', 'Profile updated'), ('STOCK_IN', 'Stock in'), ('STOCK_OUT', 'Stock out'), ('GOODS_RECEIVED', 'Delivery received'), ('SALE_CREATED', 'Dispensing recorded'), ('MEDICINE_CREATED', 'Medicine added'), ('MEDICINE_UPDATED', 'Medicine edited'), ('MEDICINE_DELETED', 'Medicine deleted'), ('BATCH_CREATED', 'Batch created'), ('BATCH_UPDATED', 'Batch edited'), ('BATCH_DELETED', 'Batch deleted'), ('CATEGORY_CREATED', 'Category added'), ('SUPPLIER_CREATED', 'Supplier added'), ('SUPPLIER_UPDATED', 'Supplier edited')], db_index=True, max_length=30)),
                ('summary', models.CharField(max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
