# Generated by Django 6.0.7 on 2026-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiry_alert_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
