# Generated by Django 6.0.7 on 2026-08-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medicine_expiry_alert_days_medicine_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.medicine'),
        ),
    ]
