# Generated by Django 6.1.1 on 2026-10-05 16:26

import django.db.models.deletion
from django.db import migrations, models


def backfill_original_quantity(apps, schema_editor):
    """Best-effort: received = what is left + everything that went out."""
    Batch = apps.get_model("inventory", "Batch")
    StockMovement = apps.get_model("inventory", "StockMovement")
    from django.db.models import Sum

    for batch in Batch.objects.all():
        out = (
            StockMovement.objects.filter(batch=batch, movement_type="OUT")
            .aggregate(total=Sum("quantity"))["total"]
            or 0
        )
        batch.original_quantity = batch.quantity + out
        batch.save(update_fields=["original_quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medicine_image'),
        ('suppliers', '0002_alter_supplier_options_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['expiry_date', 'id']},
        ),
        migrations.AddField(
            model_name='batch',
            name='original_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number'), name='uniq_batch_number_per_medicine'),
        ),
        migrations.RunPython(backfill_original_quantity, migrations.RunPython.noop),
    ]
