# Generated by Django 6.1.2 on 2026-10-08 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_batch_barcode_supplier_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-movement_date', '-id']},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('RECEIVED', 'Received'), ('DISPENSED', 'Dispensed'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('COUNT_DISCREPANCY', 'Stock count discrepancy'), ('CORRECTION', 'Correction'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.medicine'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
