# Generated by Django 6.1.2 on 2026-10-08 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockmovement_options_and_more'),
        ('notifications', '0002_notification_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
